// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ2d5ggXAJAFGINzLu1Xq5_HAe6w2I-lE',
    appId: '1:65606684007:web:65716956b02653ce6673c2',
    messagingSenderId: '65606684007',
    projectId: 'latihanuts-ee471',
    authDomain: 'latihanuts-ee471.firebaseapp.com',
    databaseURL: 'https://latihanuts-ee471-default-rtdb.firebaseio.com',
    storageBucket: 'latihanuts-ee471.firebasestorage.app',
    measurementId: 'G-BRQ4JRFK21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIjV3DNChwzP-sXRRRJygVtI6IolbdBMo',
    appId: '1:65606684007:android:6f11137372bc3aac6673c2',
    messagingSenderId: '65606684007',
    projectId: 'latihanuts-ee471',
    databaseURL: 'https://latihanuts-ee471-default-rtdb.firebaseio.com',
    storageBucket: 'latihanuts-ee471.firebasestorage.app',
  );
}
