// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3vvMHDTqjvcOu0VmoVg2yn_EXgMG6vCA',
    appId: '1:203660663103:web:ec527a9eb8633310071b8a',
    messagingSenderId: '203660663103',
    projectId: 'first-app-b36de',
    authDomain: 'first-app-b36de.firebaseapp.com',
    storageBucket: 'first-app-b36de.firebasestorage.app',
    measurementId: 'G-H8TTHJBK9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxs37_CpBBqIXnh5MqslJbqrmmR-OeUM8',
    appId: '1:203660663103:android:dd9bc5798af9eab5071b8a',
    messagingSenderId: '203660663103',
    projectId: 'first-app-b36de',
    storageBucket: 'first-app-b36de.firebasestorage.app',
  );
}
